### ISSUE TITLE
Feature Request: Difficulty Curve

### ISSUE THREAD

**Issue by Chirishman** [TEAMarg/ID-28-Blob-Attack#1]
Didn't RTFM so I didn't realize you could rotate the pieces at first. Once I realized that I played until I got bored and spiked myself at 100k.

The fall-rate doesn't seem to increase at all as tetris does. Without this or some other way of ramping the difficulty there is very little challenge once you figure out the basics.

I realize that speeding up may be impractical with the limit of the short vertical space but some other difficulty increasing element is needed. Maybe trying the sideways layout?

**Comment by JO3RI** [comment]
Mmm it should increase, I'll look into this issue too when back from vacation in August :)

**Comment by JO3RI** [comment]
Fixed in version 1.8 https://github.com/TEAMarg/ID-28-Blob-Attack/releases/tag/v1.8
